#include "lut.h"

const uint8_t servoChannelLUT[96] = {
    0, // ASCII 33 (!)
    0, // ASCII 34 (")
    0, // ASCII 35 (#)
    0, // ASCII 36 ($)
    0, // ASCII 37 (%)
    0, // ASCII 38 (&)
    0, // ASCII 39 (')
    0, // ASCII 40 (()
    0, // ASCII 41 ())
    0, // ASCII 42 (*)
    0, // ASCII 43 (+)
    0, // ASCII 44 (,)
    0, // ASCII 45 (-)
    0, // ASCII 46 (.)
    0, // ASCII 47 (/)
    0, // ASCII 48 (0)
    0, // ASCII 49 (1)
    0, // ASCII 50 (2)
    0, // ASCII 51 (3)
    0, // ASCII 52 (4)
    0, // ASCII 53 (5)
    0, // ASCII 54 (6)
    0, // ASCII 55 (7)
    0, // ASCII 56 (8)
    0, // ASCII 57 (9)
    0, // ASCII 58 (:)
    0, // ASCII 59 (;)
    0, // ASCII 60 (<)
    0, // ASCII 61 (=)
    0, // ASCII 62 (>)
    0, // ASCII 63 (?)
    0, // ASCII 64 (@)
    0, // ASCII 65 (A)
    0, // ASCII 66 (B)
    0, // ASCII 67 (C)
    0, // ASCII 68 (D)
    0, // ASCII 69 (E)
    0, // ASCII 70 (F)
    0, // ASCII 71 (G)
    0, // ASCII 72 (H)
    0, // ASCII 73 (I)
    0, // ASCII 74 (J)
    0, // ASCII 75 (K)
    0, // ASCII 76 (L)
    0, // ASCII 77 (M)
    0, // ASCII 78 (N)
    0, // ASCII 79 (O)
    0, // ASCII 80 (P)
    0, // ASCII 81 (Q)
    0, // ASCII 82 (R)
    0, // ASCII 83 (S)
    0, // ASCII 84 (T)
    0, // ASCII 85 (U)
    0, // ASCII 86 (V)
    0, // ASCII 87 (W)
    0, // ASCII 88 (X)
    0, // ASCII 89 (Y)
    0, // ASCII 90 (Z)
    0, // ASCII 91 ([)
    0, // ASCII 92 (\)
    0, // ASCII 93 (])
    0, // ASCII 94 (^)
    0, // ASCII 95 (_)
    0, // ASCII 96 (`)
    1, // ASCII 97 (a)
    2, // ASCII 98 (b)
    3, // ASCII 99 (c)
    4, // ASCII 100 (d)
    0, // ASCII 101 (e)
    0, // ASCII 102 (f)
    0, // ASCII 103 (g)
    0, // ASCII 104 (h)
    0, // ASCII 105 (i)
    0, // ASCII 106 (j)
    0, // ASCII 107 (k)
    0, // ASCII 108 (l)
    0, // ASCII 109 (m)
    0, // ASCII 110 (n)
    0, // ASCII 111 (o)
    0, // ASCII 112 (p)
    0, // ASCII 113 (q)
    0, // ASCII 114 (r)
    0, // ASCII 115 (s)
    0, // ASCII 116 (t)
    0, // ASCII 117 (u)
    0, // ASCII 118 (v)
    0, // ASCII 119 (w)
    0, // ASCII 120 (x)
    0, // ASCII 121 (y)
    0, // ASCII 122 (z)
    0, // ASCII 123 ({)
    0, // ASCII 124 (|)
    0, // ASCII 125 (})
    0, // ASCII 126 (~)
    0 // ASCII 127 ()
};

const Adafruit_PWMServoDriver *servoDriverLUT[96] = {
    &servoDriver, // ASCII 33 (!)
    &servoDriver, // ASCII 34 (")
    &servoDriver, // ASCII 35 (#)
    &servoDriver, // ASCII 36 ($)
    &servoDriver, // ASCII 37 (%)
    &servoDriver, // ASCII 38 (&)
    &servoDriver, // ASCII 39 (')
    &servoDriver, // ASCII 40 (()
    &servoDriver, // ASCII 41 ())
    &servoDriver, // ASCII 42 (*)
    &servoDriver, // ASCII 43 (+)
    &servoDriver, // ASCII 44 (,)
    &servoDriver, // ASCII 45 (-)
    &servoDriver, // ASCII 46 (.)
    &servoDriver, // ASCII 47 (/)
    &servoDriver, // ASCII 48 (0)
    &servoDriver, // ASCII 49 (1)
    &servoDriver, // ASCII 50 (2)
    &servoDriver, // ASCII 51 (3)
    &servoDriver, // ASCII 52 (4)
    &servoDriver, // ASCII 53 (5)
    &servoDriver, // ASCII 54 (6)
    &servoDriver, // ASCII 55 (7)
    &servoDriver, // ASCII 56 (8)
    &servoDriver, // ASCII 57 (9)
    &servoDriver, // ASCII 58 (:)
    &servoDriver, // ASCII 59 (;)
    &servoDriver, // ASCII 60 (<)
    &servoDriver, // ASCII 61 (=)
    &servoDriver, // ASCII 62 (>)
    &servoDriver, // ASCII 63 (?)
    &servoDriver, // ASCII 64 (@)
    &servoDriver, // ASCII 65 (A)
    &servoDriver, // ASCII 66 (B)
    &servoDriver, // ASCII 67 (C)
    &servoDriver, // ASCII 68 (D)
    &servoDriver, // ASCII 69 (E)
    &servoDriver, // ASCII 70 (F)
    &servoDriver, // ASCII 71 (G)
    &servoDriver, // ASCII 72 (H)
    &servoDriver, // ASCII 73 (I)
    &servoDriver, // ASCII 74 (J)
    &servoDriver, // ASCII 75 (K)
    &servoDriver, // ASCII 76 (L)
    &servoDriver, // ASCII 77 (M)
    &servoDriver, // ASCII 78 (N)
    &servoDriver, // ASCII 79 (O)
    &servoDriver, // ASCII 80 (P)
    &servoDriver, // ASCII 81 (Q)
    &servoDriver, // ASCII 82 (R)
    &servoDriver, // ASCII 83 (S)
    &servoDriver, // ASCII 84 (T)
    &servoDriver, // ASCII 85 (U)
    &servoDriver, // ASCII 86 (V)
    &servoDriver, // ASCII 87 (W)
    &servoDriver, // ASCII 88 (X)
    &servoDriver, // ASCII 89 (Y)
    &servoDriver, // ASCII 90 (Z)
    &servoDriver, // ASCII 91 ([)
    &servoDriver, // ASCII 92 (\)
    &servoDriver, // ASCII 93 (])
    &servoDriver, // ASCII 94 (^)
    &servoDriver, // ASCII 95 (_)
    &servoDriver, // ASCII 96 (`)
    &servoDriver, // ASCII 97 (a)
    &servoDriver, // ASCII 98 (b)
    &servoDriver, // ASCII 99 (c)
    &servoDriver, // ASCII 100 (d)
    &servoDriver, // ASCII 101 (e)
    &servoDriver, // ASCII 102 (f)
    &servoDriver, // ASCII 103 (g)
    &servoDriver, // ASCII 104 (h)
    &servoDriver, // ASCII 105 (i)
    &servoDriver, // ASCII 106 (j)
    &servoDriver, // ASCII 107 (k)
    &servoDriver, // ASCII 108 (l)
    &servoDriver, // ASCII 109 (m)
    &servoDriver, // ASCII 110 (n)
    &servoDriver, // ASCII 111 (o)
    &servoDriver, // ASCII 112 (p)
    &servoDriver, // ASCII 113 (q)
    &servoDriver, // ASCII 114 (r)
    &servoDriver, // ASCII 115 (s)
    &servoDriver, // ASCII 116 (t)
    &servoDriver, // ASCII 117 (u)
    &servoDriver, // ASCII 118 (v)
    &servoDriver, // ASCII 119 (w)
    &servoDriver, // ASCII 120 (x)
    &servoDriver, // ASCII 121 (y)
    &servoDriver, // ASCII 122 (z)
    &servoDriver, // ASCII 123 ({)
    &servoDriver, // ASCII 124 (|)
    &servoDriver, // ASCII 125 (})
    &servoDriver, // ASCII 126 (~)
    &servoDriver // ASCII 127 ()
};

uint8_t getServoChannelFromLUT(uint8_t character, uint8_t *returnCode){
    if(character >= 33 && character <= 127)
        return servoChannelLUT[character - 33];
    else{
        *returnCode = 1;
        return servoChannelLUT[0];
    }
}

// Adafruit_PWMServoDriver *getServoDriverFromLUT(uint8_t character, uint8_t *returnCode){
//     if(character >= 33 && character <= 127)
//         return servoDriverLUT[character - 33];
//     else{
//         *returnCode = 1;
//         return servoDriverLUT[0];
//     }
// }